g5_logistica/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::patch('/manutencao/deletar/{id}', 'Painel\ManutencaoController@deletaManutencaoConcluida');
Route::patch('/manutencao/{id}/update', 'Painel\ManutencaoController@update');

Route::resource('/manutencao', 'Painel\ManutencaoController');

Route::get('/manutencao/editar/{id}', 'Painel\ManutencaoController@edit');




/*****************************************************************
        ROTAS ALMOXARIFADO
/*****************************************************************/

Route::resource('/almoxarifado/salvar', 'Painel\AlmoxarifadoController');

Route::get('/almoxarifado', 'Painel\AlmoxarifadoController@index');
Route::get('/almoxarifado/create', 'Painel\AlmoxarifadoController@create');
Route::get('/almoxarifado/{id}/edit', 'Painel\AlmoxarifadoController@edit');
Route::patch('/almoxarifado/{id}/update', 'Painel\AlmoxarifadoController@update');
Route::delete('/almoxarifado/{id}/destroy', 'Painel\AlmoxarifadoController@destroy');

/******************************************************************
* Rotas Painel
******************************************************************/
Route::group(['prefix' => 'painel', 'middleware' => 'auth'], function () {


  // Route::resource('nota-entrega','Painel\NotaEntregaController', ['names' => [
  //     'index' => 'nota-entrega.index',
  //     'show' => 'ver.nota'
  //     ]]);

  // Route::get('modal/manutencao', function{
  //   return view();
  // });
  Route::any('usuarios/pesquisar', 'Painel\UserController@search')->name('usuarios.search');

  Route::post('pecas', 'Painel\PecaManutencaoController@store')->name('pecas.store');
  Route::get('peca', 'Painel\PecaManutencaoController@index')->name('peca');
  Route::post('local-manutencao', 'Painel\LocalManutencaoController@store')->name('local-manutencao.store');
  Route::get('local', 'Painel\LocalManutencaoController@index')->name('local');

  Route::resource('usuarios', 'Painel\UserController');

  Route::get('nota-entrega/{id}','Painel\NotaEntregaController@show')->name('ver.nota');
  Route::get('nota-entrega','Painel\NotaEntregaController@index')->name('nota-entrega.index');
  Route::delete('nota-entrega/{id}/excluir','Painel\NotaEntregaController@destroy')->name('nota-entrega.destroy');
  Route::get('nota-entrega/{id}/restaurar','Painel\NotaEntregaController@restore')->name('nota-entrega.restore');

  // Route::get('criar-nota-entrega/{id}/criar', 'Painel\NotaEntregaController@criar')->name('nota-entrega.criar.nota');
  Route::get('criar-nota-entrega/{id}/criar', 'Painel\NotaEntregaController@criar')->name('criar.nota');
  Route::post('criar-nota/{id}/gravar', 'Painel\NotaEntregaController@gravar')->name('gravar.nota');
  Route::get('nota-entrega/{id}/editar', 'Painel\NotaEntregaController@editar')->name('editar.nota');
  Route::put('nota-entrega/{id}/atualizar', 'Painel\NotaEntregaController@atualizar')->name('atualizar.nota');
  Route::any('notas/pesquisar', 'Painel\NotaEntregaController@search')->name('nota-entrega.search');


  // Route::get('criar-nota-entrega/{id}/criar', 'Painel\NotaEntregaController@criar')->name('nota-entrega.criar.nota');
  Route::get('acessos', 'Painel\AcessoController@index')->name('acessos.index');
  Route::get('criar-acesso/{id}/criar', 'Painel\AcessoController@criar')->name('acessos.create');
  Route::post('acesso/{id}/gravar', 'Painel\AcessoController@store')->name('acessos.store');
  Route::delete('acesso/{id}/concluir', 'Painel\AcessoController@destroy')->name('acessos.destroy');
  // Route::get('criar-acesso/{id}/editar', 'Painel\AcessoController@editar')->name('editar.acesso');
  Route::put('acesso/{id}/atualizar', 'Painel\AcessoController@atualizar')->name('acessos.update');
  // Route::any('notas/pesquisar', 'Painel\NotaEntregaController@search')->name('nota-entrega.search');





  // Route::get('criar-nota-entrega/{id}/criar', 'Painel\NotaEntregaController@criar')->name('nota-entrega.criar.nota');



  Route::get('manutenção-veiculos', 'Painel\ManutencaoController@index')
      ->name('manutencao.veiculos.index');

  Route::get('manutenção-veiculo/{id}/criar', 'Painel\ManutencaoController@criar')
      ->name('manutencao.veiculos.create');

  Route::post('manutenção-veiculo/{id}/gravar', 'Painel\ManutencaoController@store')
      ->name('manutencao.veiculos.store');

  Route::delete('manutenção-veiculo/{id}/destroy', 'Painel\ManutencaoController@destroy')
      ->name('manutencao.veiculos.destroy');



  // Route::get('criar-manutencao/{id}/editar', 'Painel\ManutencaoController@editar')->name('editar.manutencao');
  Route::put('manutenção-veiculo/{id}/atualizar', 'Painel\ManutencaoController@update') //antes estava atualizar
      ->name('manutencao.veiculos.update');
  // Route::any('notas/pesquisar', 'Painel\NotaEntregaController@search')->name('nota-entrega.search');

  // Route::get('criar-nota-entrega/{id}/criar', 'Painel\NotaEntregaController@criar')->name('nota-entrega.criar.nota');
  Route::get('manutenção-old-veiculos', 'Painel\AcessoVeiculoController@index')->name('acesso.veiculos.index');
  Route::get('manutenção-old-veiculo/{id}/criar', 'Painel\AcessoVeiculoController@criar')->name('acesso.veiculos.create');
  Route::post('manutenção-old-veiculo/{id}/gravar', 'Painel\AcessoVeiculoController@store')->name('acesso.veiculos.store');
  Route::delete('manutenção-old-veiculo/{id}/concluir', 'Painel\AcessoVeiculoController@destroy')->name('acesso.veiculos.destroy');
  // Route::get('criar-acesso/{id}/editar', 'Painel\AcessoVeiculoController@editar')->name('editar.acesso');
  Route::put('manutenção-old-veiculo/{id}/atualizar', 'Painel\AcessoVeiculoController@atualizar')->name('acesso.veiculos.update');
  // Route::any('notas/pesquisar', 'Painel\NotaEntregaController@search')->name('nota-entrega.search');


  Route::get('criar-tarefa/{id}/criar', 'Painel\NotaEntregaController@criar')->name('criar.nota');
  Route::post('criar-tarefa/{id}/gravar', 'Painel\NotaEntregaController@gravar')->name('gravar.nota');
  Route::get('tarefa/{id}/editar', 'Painel\NotaEntregaController@editar')->name('editar.nota');
  Route::put('tarefa/{id}/atualizar', 'Painel\NotaEntregaController@atualizar')->name('atualizar.nota');

  Route::any('clientes/pesquisar', 'Painel\EntradaController@search')->name('entradas.search');

  Route::resource('visitantes','Painel\EntradaController', ['names' => [
    'index'   => 'entradas.index',
    'create'  => 'entradas.create',
    'store'   => 'entradas.store',
    'show'    => 'entradas.show',
    'edit'    => 'entradas.edit',
    'update'  => 'entradas.update',
    'destroy' => 'entradas.destroy',
    ]]);

  Route::resource('veiculos','Painel\EntradaVeiculoController', ['names' => [
    'index'   => 'entradas.veiculo.index',
    'create'  => 'entradas.veiculo.create',
    'store'   => 'entradas.veiculo.store',
    'show'    => 'entradas.veiculo.show',
    'edit'    => 'entradas.veiculo.edit',
    'update'  => 'entradas.veiculo.update',
    'destroy' => 'entradas.veiculo.destroy',
    ]]);

  Route::resource('caminhoes','Painel\EntradaCaminhaoController', ['names' => [
    'index'   => 'entradas.caminhao.index',
    'create'  => 'entradas.caminhao.create',
    'store'   => 'entradas.caminhao.store',
    'show'    => 'entradas.caminhao.show',
    'edit'    => 'entradas.caminhao.edit',
    'update'  => 'entradas.caminhao.update',
    'destroy' => 'entradas.caminhao.destroy',
    ]]);

    Route::any('tarefas/pesquisar', 'Painel\TaskController@search')->name('tasks.search');
    Route::resource('tarefas','Painel\TaskController', ['names' => [
      'index'   => 'tarefas.index',
      'create'  => 'tarefas.create',
      'store'   => 'tarefas.store',
      'show'    => 'tarefas.show',
      'edit'    => 'tarefas.edit',
      'update'  => 'tarefas.update',
      'destroy' => 'tarefas.destroy',
      ]]);




    });



    Route::resource('placas', 'Painel\PlacaController');

    /******************************************************************
    * Rotas de Autenticação
    ******************************************************************/

    // Auth::routes();
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    //
    // // Registration Routes...
    // Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    // Route::post('register', 'Auth\RegisterController@register');


    // Password Reset Routes...
    Route::post('password/email', [
      'as' => 'password.email',
      'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
    ]);
    Route::get('password/reset', [
      'as' => 'password.request',
      'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
    ]);
    Route::post('password/reset', [
      'as' => '',
      'uses' => 'Auth\ResetPasswordController@reset'
    ]);
    Route::get('password/reset/{token}', [
      'as' => 'password.reset',
      'uses' => 'Auth\ResetPasswordController@showResetForm'
    ]);


    /******************************************************************
    * Rotas de Autenticação
    Auth::routes();
    ******************************************************************/





    Route::get('/', 'Painel\PainelController@indexVeiculos')->name('/');
    Route::get('/painel', 'Painel\PainelController@indexVeiculos')->name('/painel');
    // Route::get('/', 'Painel\PainelController@index')->name('/');
    // Route::get('/painel', 'Painel\PainelController@index')->name('/painel');

g5_logistica/app/Http/Controllers/Painel/AcessoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Requests\Painel\AcessoFormRequest;
use App\Http\Controllers\Controller;
use App\Models\Entrada;
use App\Models\Acesso;
use Carbon\Carbon;
use App\User;
use Session;
use Auth;
use DB;

class AcessoController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public $title  = 'Acesso';
  public $route = 'acessos';
  protected $totalPage = 12;
  public $view = 'painel.acessos';

  public function __construct(Acesso $acesso)
  {
    $this->middleware('auth');
    $this->model = $acesso;

  }


  public function index()
  {
    $title =  $this->title;
    $dataAcesso = $this->model->with('entrada')
    ->where('ativo', '1')
    ->whereHas('entrada', function ($query) {
      $query->where('ativo', '=', 1);
    })->get();
    return view("{$this->view}.index",compact('title','users','dataAcesso'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function criar($id)
  {
    // dd($id);
    $tiltle = "Acesso ";
    // dd($data->nome_pesq);
    $dataAtual = Carbon::now();


    $dataAcesso = Acesso::with('entrada')
    ->where('entrada_id', $id)
      ->whereHas('entrada', function ($query) use ($id) {
      $dataAtual = Carbon::now();
      $query->where('entrada_id', $id);
    })->first();


    // dd($data);


    $acessosAtivos = Acesso::with('entrada')
    ->where('ativo', 1)
    ->whereHas('entrada', function ($query) use ($id) {
      $dataAtual = Carbon::now();
      $query->where('id', $id);
    })->count();

    $acessosFechados = Acesso::with('entrada')
    ->where('ativo', 0)
    ->whereHas('entrada', function ($query) use ($id) {
      $dataAtual = Carbon::now();
      $query->where('id', $id);
    })->count();

    // dd($acessosAtivos,$acessosFechados);
    // $prest = Entrada::with('acessos')->findOrFail($id);

    $ultimoAcesso = Acesso::with('entrada')
    ->where('date_concedido_acesso', '<' , $dataAtual)
    ->whereHas('entrada', function ($query) use ($id) {
      $dataAtual = Carbon::now();
      $query->where('date_concedido_acesso', '<' , $dataAtual)
      ->where('id', $id);
    })
    ->where('ativo', 0)
    ->orderBy('id', 'desc')
    ->pluck('date_concluido_acesso')
    ->first();

    // dd($ultimoAcesso->diffInDays($dataAtual));

    $user2 = Entrada::with('acessos')->findOrFail($id);
    $user = Entrada::with('acessos')->findOrFail($id);

    $editar = null;
    return view("{$this->view}.create",compact('tiltle','dataAcesso','editar','user','user2','acessosAtivos','acessosFechados','ultimoAcesso'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(AcessoFormRequest $request,$id)
  {
    $dataUser = new $this->model;
    $dt = Carbon::now();
    $dataUser = $request->all();
    // $dataUser['tempo_estimado'] = \Carbon\Carbon::now()->format('Y-m-d');
    $dataUser['concedido_acesso_por'] = Auth::user()->name;
    $dataUser['date_concedido_acesso'] = \Carbon\Carbon::now()->format('Y-m-d H:i:s');

    if ($dataUser['tempo_estimado'] == 10) {
      $dataUser['tempo_estimado'] = $dt->addMinutes(10);
    }elseif ($dataUser['tempo_estimado'] == 30) {
      $dataUser['tempo_estimado'] = $dt->addMinutes(30);
    }elseif ($dataUser['tempo_estimado'] == 60) {
      $dataUser['tempo_estimado'] = $dt->addMinutes(60);
    }elseif ($dataUser['tempo_estimado'] == '5h') {
      $dataUser['tempo_estimado'] = $dt->addMinutes(300);
    }else {
      $dataUser['tempo_estimado'] = '';
    }
    // dd($dataUser);
    // if ($dataUser['nascimento'] == null) {
    //   $dataUser['nascimento'] == null;
    // }else {
    //   $dataUser['nascimento'] = str_replace('/', '-', $dataUser['nascimento']);
    //   $dataUser['nascimento'] = date('Y-m-d', strtotime($dataUser['nascimento']));
    // }
    $dataUser['entrada_id'] = $request['id'];

    $insert = $this->model->create($dataUser);

    if ($insert) {


      return redirect()
      ->route('/painel')
      ->with(['status' => 'Entrada cadastrada com sucesso!']);
    } else {
      return redirect()
      ->route('acessos.create', ['id' => $id])
      ->withErrors(['errors' => 'Falha ao cadastrar Entrada!, veja a conexão de Internet!'])
      ->withInput();
    }
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    //
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    //
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    //
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    $dataUser = $this->model->findOrFail($id);
    $dataUser['ativo']= 0;
    $dataUser['concluido_acesso_por']= Auth::user()->name;
    $dataUser['date_concluido_acesso'] = \Carbon\Carbon::now()->format('Y-m-d H:i:s');
    // dd($dataUser);
    $dataUser->save();
    // Session::flash('flash_message','Adiantamento excluído com sucesso');
    return redirect()->back()->with(['delete' => 'Acesso concluído com sucesso!']);;
  }
}

g5_logistica/app/Http/Controllers/Painel/PlacaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Placa;

class PlacaController extends Controller
{
  public function __construct(Placa $placa)
  {
    $this->middleware('auth');
    $this->model = $placa;

  }
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    return view ('painel.placas.index');
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    //
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {
    $dataUser = new $this->model;

    $dataUser = $request->all();
  }

  /**
  * Display the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    //
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    //
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    //
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  int  $id
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    //
  }
}

g5_logistica/resources/views/painel/entradasCaminhao/create-edit.blade.php
@extends('layouts.layout.template')
@push('ck-editor')
  <script src="{{asset('assets/ckeditor/ckeditor.js')}}"></script>
@endpush
@section('content')


  <div class="row">
    <div class="col-md-6 text-left">
      <h4 class="breadcrumb-title">{{$user->nome or 'Novo Veículo'}}</h4>
    </div>
    <div class="col-md-6">
      <ol class="breadcrumb hidden-xs text-right mt1">
        <li><a href="{{url('/painel')}}">Home</a></li>
        <li><a href="{{route('entradas.veiculo.index')}}">Veículos</a></li>
        <li class="active"><a href="#">{{$user->nome or 'Novo Veículo'}}</a></li>
      </ol>
    </div>
  </div>

  {{-- <div class="container">
  @if( isset($user) )
  @include('layouts.userImageCard')
@endif
</div> --}}
<div class="col-md-12">

  @include('painel.entradasCaminhao.form')

</div>

@endsection

@push('stack-css')
  <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
  <link href="{{asset('assets/js/plugins/prism/prism.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
  <link href="{{asset('assets/js/plugins/perfect-scrollbar/perfect-scrollbar.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
  <link href="{{asset('assets/js/plugins/chartist-js/chartist.min.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
  <link href="{{asset('assets/js/plugins/dropify/css/dropify.min.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
@endpush

@push('stack-js')


  <script type="text/javascript">


  function mascara(t, mask){
    var i = t.value.length;
    var saida = mask.substring(1,0);
    var texto = mask.substring(i)
    if (texto.substring(0,1) != saida){
      t.value += texto.substring(0,1);
    }
  }

  $( function() {
    $( "#datetimepicker" ).datepicker({
      format: 'dd/mm/yyyy',
      language: 'pt-BR'
    });
  } );




  </script>


  <style>
  #my_camera{
    width: 213px;
    height: 160px;
    border: 1px solid #4577b3;
  }
  </style>


  <script type="text/javascript" src="{{asset('assets/webcamjs/webcam.min.js')}}"></script>


  <!-- Code to handle taking the snapshot and displaying it locally -->
  <script language="JavaScript">

  // Configure a few settings and attach camera
  function configure(){
    Webcam.set({
      width: 213,
      height: 160,
      image_format: 'jpeg',
      jpeg_quality: 90
    });
    Webcam.attach( '#my_camera' );
  }
  // A button for taking snaps


  // preload shutter audio clip
  var shutter = new Audio();
  shutter.autoplay = false;
  shutter.src = navigator.userAgent.match(/Firefox/) ? 'shutter.ogg' : 'shutter.mp3';

  function take_snapshot() {
    // play sound effect
    shutter.play();

    // take snapshot and get image data
    Webcam.snap( function(data_uri) {
      // display results in page
      document.getElementById('results').innerHTML =
      '<img id="imageprev" src="'+data_uri+'"/>';

      var raw_image_data = data_uri.replace(/^data\:image\/\w+\;base64\,/, '');

      document.getElementById('imagem').value = raw_image_data;
      document.getElementById('myform').submit();


    } );

  }

  function saveSnap(){
    // Get base64 value from <img id='imageprev'> source
    var base64image = document.getElementById("imageprev").src;

    Webcam.upload( base64image, '{{route('usuarios.store')}}', function(code, text) {
      console.log('Save successfully');
      console.log(text);
    });

  }



  <script type="text/javascript" src="{{asset('/assets/js/jquery.maskedinput.min.js')}}"></script>
  <script type="text/javascript">
  jQuery(function($){

    $("#cpf").mask("999.999.999-99");
    $("#placa").mask("aaa-9999");

    $("#cnpj").mask("99.999.999/9999-99");
    $("#datetimepicker").mask("99/99/9999");

  });
  </script>
  <script type="text/javascript">


  function mascara(t, mask){
    var i = t.value.length;
    var saida = mask.substring(1,0);
    var texto = mask.substring(i)
    if (texto.substring(0,1) != saida){
      t.value += texto.substring(0,1);
    }
  }

  $( function() {
    $( "#datetimepicker" ).datepicker({
      format: 'dd/mm/yyyy',
      language: 'pt-BR'
    });
  } );
  </script>



@endpush

g5_logistica/resources/views/painel/entradasCaminhao/formIndex.blade.php
<div class="col-md-12" style="margin-top:10px;">
  <div class="panel panel-default">
    <div class="table-responsive">
      <table class="table table-striped table-hover table-responsive" id="myTable">
        <hr>
        <h1 class="text-center">Caminhões Cadastrados</h1>
        <thead>
          <tr>
            <th>Cod</th>
            <th class="text-center">Manutenção</th>
            <th>Placa</th>
            <th>Foto</th>
            <th>Cor</th>
            <th>Observação</th>
            <th>Modelo</th>
            <th>Cadastrado por:</th>
            <th>Data | Hora Cadastro</th>
            <th class="text-center" class="center">Ações</th>
          </tr>
        </thead>

        <tbody>
          @forelse($data as $user)
            <tr>
              <td>{{$user->id}}</td>
              <td style="text-align: center; vertical-align: middle">
                <a href="{{route('manutencao.veiculos.create',$user->id)}}"
                  class="btn btn-warning btn-lg" title="Cadastrar Manutenção">
                  <i class="fa fa-bolt fa-fw fa-3x" aria-hidden="true"></i>
                </a>
              </td>
              <td>{{$user->plate}}</td>
              <td style="text-align: center; vertical-align: middle, max-width: 50px">
                @if($user->image == null and $user->chassis == null )
                  <div class="m-b-sm"><img alt="image" class="img-rounded" src="{{asset('assets/img/empi.png')}}" style="max-width:96px;"></div>
                @elseif ($user->image == null and $user->chassis == 'Caminhão')
                  <div class="m-b-sm"><img alt="image" class="img-rounded" src="{{asset('assets/img/truck.png')}}" style="max-width:96px;"></div>
                @else
                  <div class="m-b-sm"><img alt="image" class="img-rounded" src="{{asset('assets/uploads/veiculos/'.$user->image)}}" style="max-width:96px;"></div>
                @endif
              </td>
              <td>{{$user->color}}</td>
              <td>{!!$user->observacao!!}</td>
              <td>{{$user->model}}</td>

              <td>
                {!! $user->user->name!!}
              </td>
              <td>
                {!! \Carbon\Carbon::parse($user->created_at)->format('d/m/Y | H:i') !!}
              </td>

              <td class="text-center" style="width:16%;">
                {{Form::open(['route'=>['entradas.veiculo.destroy',$user->id], 'method'=>'DELETE'])}}
                <a class="btn btn-default btn-sm" title="Editar: {{$user->nome}}"   href='{{route('entradas.veiculo.edit',$user->id)}}'><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

                <a class="btn btn-default btn-sm" title="Ver: {{$user->nome}}"   href='{{route('entradas.veiculo.show',$user->id)}}'><i class="fa fa-eye" aria-hidden="true"></i></a>

                {{ Form::button('<i class="fa fa-trash" aria-hidden="true"></i>', ['class' => 'btn btn-default btn-sm', 'title'=>'Excluir', 'role' => 'button', 'type' => 'submit', 'onclick'=>"return confirm('Tem certeza que deseja excluir o veículo: $user->plate?')"]) }}
                {{Form::close()}}
              </td>
            </tr>
          @empty
            <div class="col-md-12 text-center">
              <h1>
                <p>Nenhum Caminhão Cadastrado</p>
              </h1>
            </div>
          @endforelse
        </tbody>
      </div>
    </div>
  </div>

g5_logistica/resources/views/painel/entradasCaminhao/index.blade.php
@extends('layouts.layout.template')
@section('title', 'Usuários')

@section('content')

  <!-- Search for small screen -->

  @include('layouts.breadcrumb-caminhao')


  <div class="section">
    @include('layouts.success')
    @include('layouts.session')

    @include('layouts.cadastrar-caminhao')

    <div class="col-md-12">
      @if( Session::has('success') )
        <div class="alert alert-success hide-msg" style="float: left; width: 100%; margin: 10px 0px;">
          {{Session::get('success')}}
        </div>
      @endif
    </div>
    @include('painel.entradasCaminhao.formIndex')

    @endsection
    @push('stack-js')
      @include('layouts.paginacaoPontos')
    @endpush